### ISSUE TITLE
[DOC] -  Install and configure keycloack

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari-docs#38]
## Summary
Accurate documentation detailing:

- How do groups and roles work. Is there a difference
- Explain special groups i.e. currently Admin/Developer/Analyst
- How do I add/remove people to QHub. (ideally, this should be doable by anyone in the admin group) not just with the root password.
- How are groups and shared folders connected.

## Tasks to complete

- [ ] write documentation for the above points
- [ ] evaluate which parts of the current [docs](https://docs.qhub.dev/en/latest/source/dev_guide/keycloak.html) might be accurate and reused
	- [ ] [login](https://docs.qhub.dev/en/stable/source/installation/login.html) would need complete update/rewrite

**Comment by iameskild** [comment]
I believe all we need to do is add an update about `Roles vs Groups` to the current docs (transfer them here) and we should be good to go 👍

**Comment by trallard** [comment]
@viniciusdc is splitting the old docs and adopting diataxis
